---
title: "Fig1_extdataFig1"
output: html_document
---


**Load the 'treated_samples.rds' object:**

``` 
 treated_samples<-readRDS(file = file.path(base_dir, "treated_samples.rds"))
```

**Fig.1d & EDF1h:** Correlation with individual variants.

The data for both DMS and individual measurements of the validation variants is stored in 'all_validation_variants' dataframe. Load it and plot the correlation.
```
  all_validation_variants<-readRDS(file = file.path(base_dir, "./all_validation_variants.rds"))

      ggplot(all_validation_variants[!sanger%chin%c("Col.78") & ceiling=="no"], aes(y = DMS, x = mean_RT_validation)) + geom_point(color='black', size=5) +
        geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=10) +  
        geom_point(data=all_validation_variants[sanger=="Col.78"], aes(y = DMS, x = mean_RT_validation), size=5) + xlab("Validation Readthrough (%)") + ylab("DMS Readthrough (%)") + p +            theme(text = element_text(size=25))
        
   
      ggplot(all_validation_variants, aes(y = DMS, x = mean_RT_validation)) + geom_point(color='black', size=5) +
        geom_smooth(method = "loess", span=.9, se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=10) + 
        geom_hline(yintercept = 5.7, linetype = "dashed", color = "black", size=1) +
        geom_point(data=all_validation_variants[ceiling=="yes"], aes(y = DMS, x = mean_RT_validation), size=5, color="#C0C0C0") + xlab("Validation Readthrough (%)") + ylab("DMS Readthrough         (%)") + p + theme(text = element_text(size=25))
     
``` 
**Fig.1e:** Readthrough % across cell lines

```  
allcelllines_DVCs<-readRDS(file = file.path(base_dir, "allcelllines_DVCs.rds"))

      p1<-ggplot(allcelllines_DVCs[!is.na(RT_HeLa) & Replicate==1], aes(y = RT_HEK, x = RT_HeLa, label=sanger)) + geom_point(size=5) + p +
        geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=8) + theme(text = element_text(size=20))
      
      p2<-ggplot(allcelllines_DVCs[!is.na(RT_HeLa) & Replicate==1], aes(y = RT_HEK, x = RT_MCF7, label=sanger)) + geom_point(size=5) + p +
        geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=8) + theme(text = element_text(size=20))
      
      p3<-ggplot(allcelllines_DVCs[!is.na(RT_HeLa) & Replicate==1], aes(y = RT_MCF7, x = RT_HeLa, label=sanger)) + geom_point(size=5) + p +
        geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=8) + theme(text = element_text(size=20))
      ggarrange(p1,p2,p3, ncol=1)
```      
      
**Fig.1f:** Correlation with literature datasets

Import the excel with the dataset (manually copied it from the supplementary files of Iwone.et.al paper)
``` 
   Bidou_DMD<-readRDS(file = file.path(base_dir, "Bidou_DMD.rds"))
   Pranke_2023_G418<-readRDS(file = file.path(base_dir, "Pranke_2023_G418.rds"))
   Luna_PTEN<-readRDS(file = file.path(base_dir, "allcelllines_DVCs.rds"))
   reporter_validation<-readRDS(file = file.path(base_dir, "reporter_validation.rds"))
   floquet_2011<-readRDS(file = file.path(base_dir, "floquet_2011.rds"))
  
``` 
Correlation plot:
``` 
       
    xaxis<-"DMS Readthrough (%)"
    # DMS_Pranke_2018:
      p1<-ggplot(treated_samples[!is.na(Pranke2018_mean) & treatment=="Gentamicin" & replicate==2,], aes(x=RT, y=Pranke2018_mean)) + geom_point(color='black', size=5) + geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=8) + labs(x="", y="Pranke et al. (2018) Readthrough (%)") + ggtitle("CFTR / Gentamicin") + p + theme(text = element_text(size=20))
    
    # DMS_Bidou:
      p2<-ggplot(Pranke_2023_G418, aes(y=Pranke_RT, x=RT, label=mutation_identifier_short)) + geom_point(color='black', size=5) + geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=8) + labs(x="", y="Pranke et al. (2023) Readthrough (%)") + ggtitle("CFTR / G418, ELX-02") + p + theme(text = element_text(size=20)) 
    
    # DMS_Pranke_2023:
      p3<-ggplot(Bidou_DMD, aes(x=RT, y=Gentamicin_RT, label=mutation_identifier_short)) + geom_point(color='black', size=5) + geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=8) + labs(x="", y="Bidou et al. Readthrough (%)") + ggtitle("DMD / Gentamicin") + p + theme(text = element_text(size=20))
    
    # DMS_Luna:
      p4<-ggplot(Luna_PTEN[!is.na(Readthrough_Luna_et.al)], aes(x=RT, y=Readthrough_Luna_et.al, label=mutation_identifier_short)) + geom_point(color='black', size=5) + geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=8) + labs(x="", y="Luna et al. Readthrough (%)") + ggtitle("PTEN / G418") + p + theme(text = element_text(size=20))
    
    # DMS_Floquet:
      p5<-ggplot(floquet_2011, aes(x=RT, y=floquet_RT, label=mutation_identifier_short)) + geom_point(color='black', size=5) + geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=8) + labs(x=xaxis, y="Floquet et al. Readthrough (%)") + ggtitle("TP53 / G418") + p + theme(text = element_text(size=20))
    
    # Reporter validation.
      p6<-ggplot(reporter_validation, aes(x=Literature, y=RT_eff, label=genes)) + geom_point(color='black', size=5) + geom_smooth(method = "lm", se = FALSE, color="red") + stat_cor(aes(label = ..r.label..), method = "pearson", size=8) + labs(x=xaxis, y="Green & Loughran et al. Readthrough (%)") + ggtitle("Reporter validation / None") + p + theme(text = element_text(size=20))

    p7<-ggarrange(p1,p2,p3,p4,p5,p6, nrow=3, ncol=2) 
``` 
      
    
    
**Extended Data Fig.1b:** Calculate the interreplicate correlations.

We discard the subset of variants with low coverage (<25reads across bins). Store the rest of variants in the c1,c2,...,c9 (rep2) dtbls, each datatable belongs to one drug. Then join the 9 datatables into interreplicate_correlations dtbl, and plot:

``` 
a1<-treated_samples[replicate==2 & treatment=="SJ6986" & reads_allbins>25, fitness_rep]
b1<-treated_samples[replicate==1 & treatment=="SJ6986" & nt_seq%chin%c(treated_samples[replicate==2 & treatment=="SJ6986" & reads_allbins>25, nt_seq]), fitness_rep]
c1<-data.frame(rep1=b1, rep2=a1, treatment="SJ6986")

a2<-treated_samples[replicate==2 & treatment=="SRI" & reads_allbins>25, fitness_rep]
b2<-treated_samples[replicate==1 & treatment=="SRI" & nt_seq%chin%c(treated_samples[replicate==2 & treatment=="SRI" & reads_allbins>25, nt_seq]), fitness_rep]
c2<-data.frame(rep1=b2, rep2=a2, treatment="SRI")

a3<-treated_samples[replicate==2 & treatment=="Clitocine" & reads_allbins>25, fitness_rep]
b3<-treated_samples[replicate==1 & treatment=="Clitocine" & nt_seq%chin%c(treated_samples[replicate==2 & treatment=="Clitocine" & reads_allbins>25, nt_seq]), fitness_rep]
c3<-data.frame(rep1=b3, rep2=a3, treatment="Clitocine")

a4<-treated_samples[replicate==2 & treatment=="DAP" & reads_allbins>25, fitness_rep]
b4<-treated_samples[replicate==1 & treatment=="DAP" & nt_seq%chin%c(treated_samples[replicate==2 & treatment=="DAP" & reads_allbins>25, nt_seq]), fitness_rep]
c4<-data.frame(rep1=b4, rep2=a4, treatment="DAP")

a5<-treated_samples[replicate==2 & treatment=="CC90009" & reads_allbins>25, fitness_rep]
b5<-treated_samples[replicate==1 & treatment=="CC90009" & nt_seq%chin%c(treated_samples[replicate==2 & treatment=="CC90009" & reads_allbins>25, nt_seq]), fitness_rep]
c5<-data.frame(rep1=b5, rep2=a5, treatment="CC90009")

a6<-treated_samples[replicate==2 & treatment=="G418" & reads_allbins>25, fitness_rep]
b6<-treated_samples[replicate==1 & treatment=="G418" & nt_seq%chin%c(treated_samples[replicate==2 & treatment=="G418" & reads_allbins>25, nt_seq]), fitness_rep]
c6<-data.frame(rep1=b6, rep2=a6, treatment="G418")

a7<-treated_samples[replicate==2 & treatment=="Gentamicin" & reads_allbins>25, fitness_rep]
b7<-treated_samples[replicate==1 & treatment=="Gentamicin" & nt_seq%chin%c(treated_samples[replicate==2 & treatment=="Gentamicin" & reads_allbins>25, nt_seq]), fitness_rep]
c7<-data.frame(rep1=b7, rep2=a7, treatment="Gentamicin")

a8<-treated_samples[replicate==2 & treatment=="FUr" & reads_allbins>25, fitness_rep]
b8<-treated_samples[replicate==1 & treatment=="FUr" & nt_seq%chin%c(treated_samples[replicate==2 & treatment=="FUr" & reads_allbins>25, nt_seq]), fitness_rep]
c8<-data.frame(rep1=b8, rep2=a8, treatment="FUr")

a9<-treated_samples[replicate==2 & treatment=="Untreated" & reads_allbins>25, fitness_rep]
b9<-treated_samples[replicate==1 & treatment=="Untreated" & nt_seq%chin%c(treated_samples[replicate==2 & treatment=="Untreated" & reads_allbins>25, nt_seq]), fitness_rep]
c9<-data.frame(rep1=b9, rep2=a9, treatment="Untreated")

interreplicate_correlations<-rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(c1,c2),c3),c4),c5),c6),c7),c8),c9)

```
Alternatively, directly load the 'interreplicate_correlations.rds' object from base_dir:

```
  interreplicate_correlations<-readRDS(file = file.path(base_dir, "./interreplicate_correlations.rds"))

```

Plot drugs separately:
```
ggplot(interreplicate_correlations) + geom_hex(aes(y=rep1, x=rep2), bins=70) + scale_fill_viridis(limits = c(0, 100), oob = scales::squish, alpha = 0.85) +
  theme(strip.background = element_rect(color="white", fill="white", size=0, linetype="solid"), panel.spacing.y = unit(.5, "lines"),
        legend.position = "none", text = element_text(size = 15), axis.title.x = element_text(size=20), axis.title.y = element_text(size=20), plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  facet_wrap(~treatment, nrow=3, scales = "free") + labs(y="Replicate 1", x="Replicate 2") + stat_cor(aes(y=rep1, x=rep2, label = ..r.label..), size=4, label.y.npc=c(1,1)) #title=paste("Clitocine \nr2:", round(mean(R2_1),2), sep="")
``` 

Plot all drugs together:

``` 
  ggplot(interreplicate_correlations) + geom_hex(aes(y=rep1, x=rep2), bins=70) + scale_fill_viridis(limits = c(0, 100), oob = scales::squish, alpha = 0.85) +
    stat_cor(aes(y=rep1, x=rep2, label = ..r.label..), size=4, label.y.npc=c(1,1)) 
``` 


**Extended Data Fig.1c,d:** Viability and readthrough titration curves
  

```
   toxicity<-readRDS(file = file.path(base_dir, "toxicity.rds"))
   RT_vs_concentration<-readRDS(file = file.path(base_dir, "RT_vs_concentration.rds"))

        ggplot(toxicity[Treatment!="Untreated"], aes(x=log_concentration, y=mean)) + geom_point(aes(color=Used), size=3) + geom_line(size=.5) + ylim(0,105)+ geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd)) + xlab("log2(Drug concentration)") + ylab("% Cell viability (normalised to untreated cells)") + facet_wrap(~Treatment, scales="free", nrow=3) + p
       
        ggplot(RT_vs_concentration, aes(x=log_concentration, y=mean)) + geom_point(aes(color=Used), size=3) + geom_line(size=.5) + geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd)) + xlab("log2(Drug concentration)") + ylab("Readthrough (%)") + facet_wrap(~Treatment, scales="free", nrow=3) + p
      

``` 

**Extended Data Fig.1e:** Interdrugs correlations.

```
  a<-treated_samples[treatment=="FUr" & replicate==1 & reads_allbins>10, c("identifier", "RT")]
  b<-treated_samples[treatment=="CC90009" & replicate==1 & reads_allbins>10,  c("identifier", "RT")]
  c<-treated_samples[treatment=="Gentamicin" & replicate==1 & reads_allbins>10,  c("identifier", "RT")]
  d<-treated_samples[treatment=="Untreated" & replicate==1 & reads_allbins>10,  c("identifier", "RT")]
  e<-treated_samples[treatment=="G418" & replicate==1 & reads_allbins>10,  c("identifier", "RT")]
  f<-treated_samples[treatment=="SRI" & replicate==1 & reads_allbins>10,  c("identifier", "RT")]
  g<-treated_samples[treatment=="SJ6986" & replicate==1 & reads_allbins>10,  c("identifier", "RT")]
  h<-treated_samples[treatment=="Clitocine" & replicate==1 & reads_allbins>10,  c("identifier", "RT")]
  i<-treated_samples[treatment=="DAP" & replicate==1 & reads_allbins>10,  c("identifier", "RT")]
  
```
Alternatively, directly load the 'interdrugs_correlation.rds' object from base_dir:

```
  interdrugs_correlation<-readRDS(file = file.path(base_dir, "./interdrugs_correlation.rds"))
```

Plot:

```
  interdrugs_correlation<-left_join(left_join(left_join(left_join(left_join(left_join(left_join(left_join(a,b, by="identifier"),c, by="identifier"),d, by="identifier"),e, by="identifier"),f, by="identifier"),g, by="identifier"),h, by="identifier"),i, by="identifier")
  colnames(interdrugs_correlation)<-c("identifier", "FUr", "CC90009", "Genta", "Untreated", "G418","SRI", "SJ6986", "Clitocine", "DAP")
  ggpairs(interdrugs_correlation, columns=c("FUr", "CC90009", "Genta", "Untreated", "G418","SRI", "SJ6986", "Clitocine", "DAP"),na.rm=T, lower = list(continuous = "smooth"))
```


**Extended Data Fig.1f:** Generate a table with the correlation of all features tested during model design/optimization vs readthrough.

I have to use two different metrics for the continuous and discrete variables: correlation (for continous variables) and krustal-wallis (chi-squared) for the discrete variables.
  
variables_continuous_numeric contains the columns indexes of the treated_samples for the continuous features.
```
  variables_continuous<-c("tAI_up_1aa", "tAI_up_2aas", "tAI_up_3aas", "tAI_up_4aas", "tAI_up_5aas", "tAI_up_10aas", "tAI_up_15aas", "CAI_up_1aa", "CAI_up_2aas", "CAI_up_3aas", "CAI_up_4aas", "CAI_up_5aas", "CAI_up_10aas", "CAI_up_15aas", "GCperc_2aas",  "GCperc_3aas", "GCperc_4aas", "GCperc_5aas", "GCperc_10aas", "GCperc_15aas", "deltaG_OA", "deltaG_mFold")
  
  variables_continuous_numeric<-c()
  for (i in 1:length(variables_continuous)){
    variables_continuous_numeric<-c(variables_continuous_numeric, which(colnames(treated_samples)==variables_continuous[i]))
  } 
  statistics_continuous<-c()
  for (i in variables_continuous_numeric){
    statistics_continuous<-c(statistics_continuous, round(cor(treated_samples[replicate==1, RT],as.data.frame(treated_samples[replicate==1])[,i], use = "complete.obs"),3))
  }
  statistics_continuous<-data.frame(Feature=variables_continuous, correlation=statistics_continuous) 
  statistics_continuous<-statistics_continuous %>% arrange(desc(abs(correlation)))
```
 
variables_discrete_numeric contains the columns indexes of the treated_samples for the discrete features.
  
```  
variables_discrete<-c("stop_type", "down_1nt","down_2nt", "down_3nt", "down_4nt", "down_5nt", "down_6nt","down_7nt", "down_8nt", "down_12nt", "down_123nt", "down_1234nt","up_1nt", "up_2nt", "up_3nt", "up_12nt", "up_123nt", "up_codon_2", "up_codon_4", "up_codon_5", "up_codon_3", "up_aa", "up_aa2", "proline_stretch")
  variables_discrete_numeric<-c()
  for (i in 1:length(variables_discrete)){
    variables_discrete_numeric<-c(variables_discrete_numeric, which(colnames(treated_samples)==variables_discrete[i]))
  }
  statistics_discrete<-c()
  for (i in variables_discrete_numeric){
    statistics_discrete<-c(statistics_discrete, round(as.vector(kruskal.test(treated_samples[!is.na(RT) & replicate==1, RT]~as.data.frame(treated_samples[!is.na(RT) & replicate==1])[,i])$statistic),2))
  }
  statistics_discrete<-data.frame(Feature=variables_discrete, `chi-squared`=statistics_discrete)
  statistics_discrete<-statistics_discrete %>% arrange(desc(abs(chi.squared)))
```
Plot it:  

```
  ggplot(statistics_continuous, aes(x=Feature, y=correlation)) + geom_bar(stat="identity", fill="grey") + scale_x_discrete(limits = statistics_continuous$Feature) + 
    theme(axis.text.x = element_text(angle=90, hjust=1, vjust=.5)) + p
  
  ggplot(statistics_discrete, aes(x=Feature, y=chi.squared)) + geom_bar(stat="identity", fill="grey") + scale_x_discrete(limits = statistics_discrete$Feature) + 
    theme(axis.text.x = element_text(angle=90, hjust=1, vjust=.5)) + p
```
