---
title: "Fig4_extdataFig4"
output: html_document
---


**Load the 'treated_samples.rds' object:**

``` 
  treated_samples<-readRDS(file = file.path(base_dir, "treated_samples.rds"))
```


**The code below generates the plots for all 9 drugs, not only the 6 drugs mentioned in the main text.**

**Fig.4a:** Drug-specific models: this loop runs the model for the 9 drugs (10-crossvalidation rounds). 

First, it stores the r2s in drug_specific_r2s dataframe. 

Secondly, in 'llista' we store the all_predictions for the 9 drugs, which contains all the predictions and observed values of the heldout data across the 10 crossvalidation rounds. After the loop, rbind all 9 'llista' entries and store the info in 'all_drugs_predictions'. 'all_drugs_predictions' object contains all the info to plot Fig.4a.

Using the saveRDS function models can be stored in the 'generated_drugspecific_models' subdirectory on base_dir. They will be needed again for Fig.6.

```
      drugs<-c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI", "Untreated")
      drug_specific_r2s<-c(); coefficients<-list()
      llista<-list() 
      
     for (j in 1:length(drugs)){
     set.seed(721); training.samples_1 <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
       createDataPartition(p = 0.9, list = FALSE, times=10)
      R2_1=c()
      all_predictions<-data.frame()
      for (i in 1:ncol(training.samples_1)){
        train.data_1  <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
        test.data_1 <-  treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
        model_1 <- glm(RT_binomial ~ 0 + stop_type + down_123nt + up_123nt + stop_type:down_123nt, train.data_1, family="binomial")
        saveRDS(model_1, file = file.path(base_dir, paste0("Fig4/generated_drugspecific_models/model_nt123_", drugs[j],".rds")))
        predictions_1 <- predict(model_1, test.data_1, type = "response")
        R2_1 = c(R2_1, cor(predictions_1, test.data_1$RT_binomial)^2)
        tmp_predictions<-data.frame(predicted=predictions_1*100, observed=test.data_1$RT_binomial*100, treatment=drugs[j])
        all_predictions<-rbind(all_predictions, tmp_predictions)
      }
      llista[[j]]<-all_predictions
      drug_specific_r2s[j]<-mean(R2_1)
      }
      drug_specific_r2s<-data.frame(treatment=drugs, r2=drug_specific_r2s)
      
      all_drugs_predictions<-data.frame()
      for (j in 1:length(drugs)){all_drugs_predictions<-rbind(all_drugs_predictions, llista[[j]])}
```

Alternatively, you can load the already generated models.rds and 'all_drugs_predictions' objects from base_dir:

```
 treated_samples<-readRDS(file = file.path(base_dir, "treated_samples.rds"))

  model_nt123_Clitocine<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/model_nt123_Clitocine.rds"))
  model_nt123_DAP<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/model_nt123_DAP.rds"))
  model_nt123_G418<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/model_nt123_G418.rds"))
  model_nt123_SRI<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/model_nt123_SRI.rds"))
  model_nt123_SJ6986<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/model_nt123_SJ6986.rds"))
  model_nt123_CC90009<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/model_nt123_CC90009.rds"))
  model_nt123_Gentamicin<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/model_nt123_Gentamicin.rds"))
  model_nt123_FUr<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/model_nt123_FUr.rds"))
  
    all_drugs_predictions<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/all_drugs_predictions.rds"))
```
Plot:

```
ggplot(all_drugs_predictions[!treatment%chin%c("Untreated", "FUr", "Gentamicin")]) + geom_hex(aes(y=observed, x=predicted), bins=70) + scale_fill_viridis(limits = c(0, 100), oob = scales::squish, alpha = 0.85) + labs(y="Observed", x="Predicted") + stat_cor(aes(y=observed, x=predicted, label = ..rr.label..), size=4, label.y.npc=c(1,1)) +
          p + theme(panel.spacing.y = unit(.5, "lines"), legend.position = "none", text = element_text(size = 15), axis.title.x = element_text(size=15), axis.title.y = element_text(size=15)) +
          facet_wrap(~treatment, nrow=3, scales = "free") 
```
        
        
**Fig.4b:** General drug model (merging all datapoints from Clitocine, CC90009, DAP, G418, SJ6986 and SRI). 3 different model versions.

**Drug-agnostic model:** predicted and observed values for the heldout data across the 10 crossvalidation rounds are stored in 'genmodel_predictions_drugagnostic_6drugs'.
```
      set.seed(721); training.samples_1 <- treated_samples[!treatment%in%c("Untreated", "Gentamicin", "FUr") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
        createDataPartition(p = 0.9, list = FALSE, times=10)
      R2_genmodel_crossvalidation_drugagnostic_6drugs=c()
      genmodel_predictions_drugagnostic_6drugs<-data.frame()
      for (i in 1:ncol(training.samples_1)){
        train.data_1  <- treated_samples[!treatment%in%c("Untreated", "Gentamicin", "FUr") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
        test.data_1 <-  treated_samples[!treatment%in%c("Untreated", "Gentamicin", "FUr") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
        general_model_drugagnostic_6drugs <- glm(RT_binomial ~ 0 + stop_type + down_123nt + up_123nt + stop_type:down_123nt, train.data_1, family="binomial")
        predictions_1 <- predict(general_model_drugagnostic_6drugs, test.data_1, type = "response")
        R2_genmodel_crossvalidation_drugagnostic_6drugs = c(R2_genmodel_crossvalidation_drugagnostic_6drugs, cor(predictions_1, test.data_1$RT_binomial)^2)
        tmp_predictions<-data.frame(predicted=predictions_1*100, observed=test.data_1$RT_binomial*100)
        genmodel_predictions_drugagnostic_6drugs<-rbind(genmodel_predictions_drugagnostic_6drugs, tmp_predictions)
      }
      genmodel_predictions_drugagnostic_6drugs<-as.data.table(genmodel_predictions_drugagnostic_6drugs)
      genmodel_predictions_drugagnostic_6drugs[, model:="Drug agnostic"]
      
```
Alternatively, you can load the 'general_model_drugagnostic_6drugs.rds' object from base_dir:

```
general_model_drugagnostic_6drugs<-readRDS(file = file.path(base_dir, "Fig4/Models/Pan_drug_models/general_model_drugagnostic_6drugs.rds"))

```


**Drug-aware model but without drug interactions:** predicted and observed values for the heldout data across the 10 crossvalidation rounds are stored in 'genmodel_predictions_drugterm_6drugs'.

```
      set.seed(721); training.samples_1 <- treated_samples[!treatment%in%c("Untreated", "Gentamicin", "FUr") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
        createDataPartition(p = 0.9, list = FALSE, times=10)
      R2_genmodel_crossvalidation_drugterm_6drugs=c()
      genmodel_predictions_drugterm_6drugs<-data.frame()
      for (i in 1:ncol(training.samples_1)){
        train.data_1  <- treated_samples[!treatment%in%c("Untreated", "Gentamicin", "FUr") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
        test.data_1 <-  treated_samples[!treatment%in%c("Untreated", "Gentamicin", "FUr") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
        # Build the models
        general_model_drugterm_6drugs <- glm(RT_binomial ~ 0 + stop_type + down_123nt + up_123nt + stop_type:down_123nt + treatment, train.data_1, family="binomial")
        # Make predictions and compute the R2
        predictions_1 <- predict(general_model_drugterm_6drugs, test.data_1, type = "response")
        R2_genmodel_crossvalidation_drugterm_6drugs = c(R2_genmodel_crossvalidation_drugterm_6drugs, cor(predictions_1, test.data_1$RT_binomial)^2)
        tmp_predictions<-data.frame(predicted=predictions_1*100, observed=test.data_1$RT_binomial*100)
        genmodel_predictions_drugterm_6drugs<-rbind(genmodel_predictions_drugterm_6drugs, tmp_predictions)
      }
      genmodel_predictions_drugterm_6drugs<-as.data.table(genmodel_predictions_drugterm_6drugs)
      genmodel_predictions_drugterm_6drugs[, model:="Drug aware & interaction agnostic"]
      
```      
Alternatively, you can load the 'general_model_drugterm_6drugs.rds' object from base_dir:

```
general_model_drugterm_6drugs<-readRDS(file = file.path(base_dir, "Fig4/Models/Pan_drug_models/general_model_drugterm_6drugs.rds"))
```


**Drug-aware and interaction-aware model (the complete pan-drug model):** predicted and observed values for the heldout data across the 10 crossvalidation rounds are stored in 'genmodel_predictions_druginteractions_6drugs'.
```
      set.seed(721); training.samples_1 <- treated_samples[!treatment%in%c("Untreated", "Gentamicin", "FUr") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
        createDataPartition(p = 0.9, list = FALSE, times=10)
      R2_genmodel_crossvalidation_druginteractions_6drugs=c()
      genmodel_predictions_druginteractions_6drugs<-data.frame()
      for (i in 1:ncol(training.samples_1)){
        train.data_1  <- treated_samples[!treatment%in%c("Untreated", "Gentamicin", "FUr") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
        test.data_1 <-  treated_samples[!treatment%in%c("Untreated", "Gentamicin", "FUr") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
        general_model_druginteractions_6drugs <- glm(RT_binomial ~ 0 + stop_type + down_123nt + up_123nt + stop_type:down_123nt + treatment + treatment*stop_type + treatment*down_123nt + treatment*up_123nt + treatment*down_123nt*stop_type, train.data_1, family="binomial")
        predictions_1 <- predict(general_model_druginteractions_6drugs, test.data_1, type = "response")
        R2_genmodel_crossvalidation_druginteractions_6drugs = c(R2_genmodel_crossvalidation_druginteractions_6drugs, cor(predictions_1, test.data_1$RT_binomial)^2)
        tmp_predictions<-data.frame(predicted=predictions_1*100, observed=test.data_1$RT_binomial*100)
        genmodel_predictions_druginteractions_6drugs<-rbind(genmodel_predictions_druginteractions_6drugs, tmp_predictions)
      }
      genmodel_predictions_druginteractions_6drugs<-as.data.table(genmodel_predictions_druginteractions_6drugs)
      genmodel_predictions_druginteractions_6drugs[, model:="Drug & interaction aware"]
```      
    
Alternatively, you can load the 'general_model_druginteractions_6drugs.rds' object from base_dir:

```
  general_model_druginteractions_6drugs<-readRDS(file = file.path(base_dir, "Fig4/Models/Pan_drug_models/general_model_druginteractions_6drugs.rds"))
```
      
Unify the predictions of the 3 pan drugs models in 'all_pandrugmodels_predictions' object, which will be used to plot the observed_vs_predicted plots:
```
      all_pandrugmodels_predictions<-rbind(genmodel_predictions_drugagnostic_6drugs, genmodel_predictions_drugterm_6drugs, genmodel_predictions_druginteractions_6drug)
      all_pandrugmodels_predictions$model<-factor(all_pandrugmodels_predictions$model, levels = c("Drug agnostic", "Drug aware & interaction agnostic", "Drug & interaction aware"))
```      

Alternatively, you can load the 'all_pandrugmodels_predictions.rds' object from base_dir:

```
  all_pandrugmodels_predictions<-readRDS(file = file.path(base_dir, "Fig4/Models/Pan_drug_models/all_pandrugmodels_predictions.rds"))
```

Plot:
``` 
ggplot(all_pandrugmodels_predictions) + geom_hex(aes(y=observed, x=predicted), bins=70) + scale_fill_viridis(limits = c(0, 100), oob = scales::squish, alpha = 0.85) + labs(y="Observed", x="Predicted") + stat_cor(aes(y=observed, x=predicted, label = ..rr.label..), size=4, label.y.npc=c(1,1)) +
        p + theme(panel.spacing.y = unit(.5, "lines"), legend.position = "none", text = element_text(size = 12), axis.title.x = element_text(size=15), axis.title.y = element_text(size=15)) + facet_wrap(~model, nrow=3, scales = "free") 
``` 




**Fig.4c:** Contribution to model performance of the 8nts downstream of the PTC.

This loop runs the model for the 9 drugs (10-crossvalidation rounds) and stores the 20 r2s for each model-drug pair in ntposition_r2s object. This object is a vector, where treatments are ordered the same way than in the drugs vector.

``` 
drugs<-c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI", "Untreated")
ntposition_coeffs<-list(); ntposition_r2s<-list()
for (j in 1:length(drugs)){
  set.seed(721); training.samples_1 <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>20 & viral=="no" & !is.na(RT), RT_binomial] %>%
    createDataPartition(p = 0.9, list = FALSE, times=20)
  R2_0=c(); R2_1=c(); R2_2=c(); R2_3=c(); R2_4=c(); R2_5=c(); R2_6=c(); R2_7=c(); R2_8=c()
  coeffs_dtbl<-data.frame(a=rep(0,8), b=rep(0,8),  c=rep(0,8), d=rep(0,8), e=rep(0,8), f=rep(0,8), g=rep(0,8), h=rep(0,8), i=c(1,2,3,4,5,6,7,8))
  all_predictions<-data.frame()
  for (k in 1:ncol(training.samples_1)){
    train.data_1  <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,k], ]
    test.data_1 <-  treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,k], ]
    # Build and save the models
    model_0 <- glm(RT_binomial ~ 0 + stop_type + up_123nt, train.data_1, family="binomial")
    model_1 <- glm(RT_binomial ~ 0 + stop_type + up_123nt + down_1nt, train.data_1, family="binomial")
    model_2 <- glm(RT_binomial ~ 0 + stop_type + up_123nt + down_1nt + down_2nt, train.data_1, family="binomial")
    model_3 <- glm(RT_binomial ~ 0 + stop_type + up_123nt + down_1nt + down_2nt + down_3nt, train.data_1, family="binomial")
    model_4 <- glm(RT_binomial ~ 0 + stop_type + up_123nt + down_1nt + down_2nt + down_3nt + down_4nt, train.data_1, family="binomial")
    model_5 <- glm(RT_binomial ~ 0 + stop_type + up_123nt + down_1nt + down_2nt + down_3nt + down_4nt + down_5nt, train.data_1, family="binomial")
    model_6 <- glm(RT_binomial ~ 0 + stop_type + up_123nt + down_1nt + down_2nt + down_3nt + down_4nt + down_5nt + down_6nt, train.data_1, family="binomial")
    model_7 <- glm(RT_binomial ~ 0 + stop_type + up_123nt + down_1nt + down_2nt + down_3nt + down_4nt + down_5nt + down_6nt + down_7nt, train.data_1, family="binomial")
    model_8 <- glm(RT_binomial ~ 0 + stop_type + up_123nt + down_1nt + down_2nt + down_3nt + down_4nt + down_5nt + down_6nt + down_7nt + down_8nt + up_123nt, train.data_1, family="binomial")
    predictions_0 <- predict(model_0, test.data_1, type = "response")
    predictions_1 <- predict(model_1, test.data_1, type = "response"); predictions_2 <- predict(model_2, test.data_1, type = "response")
    predictions_3 <- predict(model_3, test.data_1, type = "response"); predictions_4 <- predict(model_4, test.data_1, type = "response")
    predictions_5 <- predict(model_5, test.data_1, type = "response"); predictions_6 <- predict(model_6, test.data_1, type = "response")
    predictions_7 <- predict(model_7, test.data_1, type = "response"); predictions_8 <- predict(model_8, test.data_1, type = "response")
    R2_0 = c(R2_0, cor(predictions_0, test.data_1$RT_binomial)^2)
    R2_1 = c(R2_1, cor(predictions_1, test.data_1$RT_binomial)^2); R2_2 = c(R2_2, cor(predictions_2, test.data_1$RT_binomial)^2)
    R2_3 = c(R2_3, cor(predictions_3, test.data_1$RT_binomial)^2); R2_4 = c(R2_4, cor(predictions_4, test.data_1$RT_binomial)^2)
    R2_5 = c(R2_5, cor(predictions_5, test.data_1$RT_binomial)^2); R2_6 = c(R2_6, cor(predictions_6, test.data_1$RT_binomial)^2)
    R2_7 = c(R2_7, cor(predictions_7, test.data_1$RT_binomial)^2); R2_8 = c(R2_8, cor(predictions_8, test.data_1$RT_binomial)^2)
  }
    ntposition_r2s[[j]]<-as.data.table(data.frame(wo_nucleotides=R2_0, nt_1=R2_1, nt_2=R2_2, nt_3=R2_3, nt_4=R2_4, nt_5=R2_5, nt_6=R2_6, nt_7=R2_7, nt_8=R2_8))
  }
  names(ntposition_r2s)<-drugs 
``` 

Calculate a p-value for each model. Each model is compared to the preivous one (i.e. r2 of model with down_1nt, down_2nt, down_3nt, down_4nt as terms, is compared to the r2 of the model with down_1nt, down_2nt, down_3nt as terms.), and pvalues are stored in 'nt_position_significance_tbl'. 
``` 
nt_1<-data.frame(drug=drugs, pval_nt1=rep(0,9)); nt_2<-data.frame(drug=drugs, pval_nt2=rep(0,9)); nt_3<-data.frame(drug=drugs, pval_nt3=rep(0,9));nt_4<-data.frame(drug=drugs, pval_nt4=rep(0,9))
nt_5<-data.frame(drug=drugs, pval_nt5=rep(0,9));nt_6<-data.frame(drug=drugs, pval_nt6=rep(0,9));nt_7<-data.frame(drug=drugs, pval_nt7=rep(0,9));nt_8<-data.frame(drug=drugs, pval_nt8=rep(0,9))
  for (i in 1:length(ntposition_r2s)) {
nt_1[i,2]<-t.test(ntposition_r2s[[i]][,"wo_nucleotides"], ntposition_r2s[[i]][,"nt_1"])$p.value
nt_2[i,2]<-t.test(ntposition_r2s[[i]][,"nt_1"], ntposition_r2s[[i]][,"nt_2"])$p.value
nt_3[i,2]<-t.test(ntposition_r2s[[i]][,"nt_2"], ntposition_r2s[[i]][,"nt_3"])$p.value
nt_4[i,2]<-t.test(ntposition_r2s[[i]][,"nt_3"], ntposition_r2s[[i]][,"nt_4"])$p.value
nt_5[i,2]<-t.test(ntposition_r2s[[i]][,"nt_4"], ntposition_r2s[[i]][,"nt_5"])$p.value
nt_6[i,2]<-t.test(ntposition_r2s[[i]][,"nt_5"], ntposition_r2s[[i]][,"nt_6"])$p.value
nt_7[i,2]<-t.test(ntposition_r2s[[i]][,"nt_6"], ntposition_r2s[[i]][,"nt_7"])$p.value
nt_8[i,2]<-t.test(ntposition_r2s[[i]][,"nt_7"], ntposition_r2s[[i]][,"nt_8"])$p.value
  }
nt_position_significance_tbl<-left_join(left_join(left_join(left_join(left_join(left_join(left_join(nt_1, nt_2, by="drug"),nt_3, by="drug"),nt_4, by="drug"),nt_5, by="drug"),nt_6, by="drug"),nt_7, by="drug"),nt_8, by="drug")
``` 

Finally, we use the ntposition_r2s list to generate the 'increase_r2s_ntposition' dtbl, which contains the mean r2 of each model-drug pair, and we use it to plot the fig.4 'increase in r2 by each nt_position' plots:

``` 
    increase_r2s_ntposition<-data.frame()
      for (j in 1:length(drugs)){increase_r2s_ntposition<-rbind(increase_r2s_ntposition, cbind(colMeans(ntposition_r2s[[j]])))}
      increase_r2s_ntposition<-cbind(increase_r2s_ntposition, rep(c("no_nt_info",  "down_1nt","down_2nt", "down_3nt", "down_4nt", "down_5nt", "down_6nt","down_7nt", "down_8nt"),9))
      increase_r2s_ntposition<-cbind(increase_r2s_ntposition, c(rep(drugs[1],9), rep(drugs[2],9), rep(drugs[3],9), rep(drugs[4],9), rep(drugs[5],9), rep(drugs[6],9), rep(drugs[7],9), rep(drugs[8],9), rep(drugs[9],9)))
      colnames(increase_r2s_ntposition)<-c("r2", "nt", "treatment")
      increase_r2s_ntposition<-as.data.table(increase_r2s_ntposition)
      increase_r2s_ntposition$nt <- factor(increase_r2s_ntposition$nt, levels = c("no_nt_info", "down_1nt", "down_2nt", "down_3nt", "down_4nt", "down_5nt", "down_6nt", "down_7nt", "down_8nt"))
  
``` 

Alternatively, you can load the 'increase_r2s_ntposition.rds' object from base_dir:

```
increase_r2s_ntposition<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/increase_r2s_ntposition.rds"))
```


Plot it: 
``` 
ggplot(increase_r2s_ntposition[!treatment%chin%c("Untreated", "Gentamicin", "FUr")], aes(y=r2, x=nt))+ geom_boxplot(color="#FF6666", alpha=1) + labs(y="Model r2", x="Nucleotide position after the PTC") + annotate("text", x = c(1,2), y = .5, label = expression("*")) + p + theme(strip.background = element_rect(color="white", fill="white", size=0, linetype="solid"), panel.spacing.y = unit(.5, "lines"), text = element_text(size = 15), axis.text.x = element_text(size=10, angle=90, hjust = 1, vjust=.5)) + facet_wrap(~treatment, scales="free", nrow=3) + ylim(0,1)
        

``` 

**Fig.4d:** ANOVA test on the nine drug-specific models.

Drop in model performance upon removal of each predictive variable while retaining all other variables in the model. Results stored in 'decrease_r2s_drugspec'.

``` 
      drugs<-c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI", "Untreated")
      list<-list()
      for (j in 1:length(drugs)){
        set.seed(721); training.samples_1 <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
          createDataPartition(p = 0.9, list = FALSE, times=9)
        R2_1=c(); R2_2=c(); R2_3=c(); R2_4=c(); R2_5=c()
        all_predictions<-data.frame()
        for (i in 1:ncol(training.samples_1)){
          train.data_1  <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
          test.data_1 <-  treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
          model_1 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + stop_type:down_123nt, train.data_1, family="binomial")
          model_2 <- glm(RT_binomial ~ down_123nt + up_123nt, train.data_1, family="binomial")
          model_3 <- glm(RT_binomial ~ stop_type + up_123nt, train.data_1, family="binomial")
          model_4 <- glm(RT_binomial ~ stop_type + down_123nt + stop_type:down_123nt, train.data_1, family="binomial")
          model_5 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt, train.data_1, family="binomial")
          predictions_1 <- predict(model_1, test.data_1, type = "response"); predictions_2 <- predict(model_2, test.data_1, type = "response")
          predictions_3 <- predict(model_3, test.data_1, type = "response"); predictions_4 <- predict(model_4, test.data_1, type = "response"); predictions_5 <- predict(model_5, test.data_1, type = "response")  
          R2_1 = c(R2_1, cor(predictions_1, test.data_1$RT_binomial)^2); R2_2 = c(R2_2, cor(predictions_2, test.data_1$RT_binomial)^2)
          R2_3 = c(R2_3, cor(predictions_3, test.data_1$RT_binomial)^2); R2_4 = c(R2_4, cor(predictions_4, test.data_1$RT_binomial)^2); R2_5 = c(R2_5, cor(predictions_5, test.data_1$RT_binomial)^2)
        }
        list[[j]]<-c(mean(R2_1), mean(R2_2), mean(R2_3), mean(R2_4), mean(R2_5))
      }
      
      decrease_r2s_drugspec<-as.data.table(rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(list[[1]], list[[2]]), list[[3]]), list[[4]]), list[[5]]), list[[6]]), list[[7]]), list[[8]]), list[[9]]))
      decrease_r2s_drugspec$treatment<-drugs
      colnames(decrease_r2s_drugspec)<-c("full_model", "stop_type", "down_123nt", "up_123nt", "stop_type*\ndown_123nt", "drugs")
      decrease_r2s_drugspec<-as.data.table(tidyr::pivot_longer(decrease_r2s_drugspec, cols=c(1:5), names_to="term")); colnames(decrease_r2s_drugspec)<-c("Treatment", "Term", "r2")
      decrease_r2s_drugspec$Term <- factor(decrease_r2s_drugspec$Term , levels = c("full_model", "stop_type", "down_123nt", "up_123nt", "stop_type*\ndown_123nt"))
``` 

Alternatively, you can load the 'decrease_r2s_drugspec.rds' object from base_dir:

```
decrease_r2s_drugspec<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/decrease_r2s_drugspec.rds"))
```


Plot it:
``` 
  ggplot(decrease_r2s_drugspec[!Treatment%chin%c("Untreated", "FUr", "Gentamicin")], aes(x=Term, y=r2, group=Treatment, color=Treatment, label=round(r2,2))) + geom_point(size=2) + geom_text(nudge_y =0.03)+ labs(x="Model terms", y="Model r2") + 
            ylim(0,.92) + drugs_colors + p + theme(legend.position = "right", legend.text=element_text(size=12), text = element_text(size = 15), axis.text.x = element_text(size = 12, angle=90, vjust = 0.5, hjust=1))

``` 


**Fig.4e:** Correlation across drugs of the drug-specific model coefficients.

Get the coefficients estimates, stddevs and ci95 for the drug-specific models without the 'stop_tpye:down_123nt' interaction term.

We do 10 crossvalidation rounds for each model, and use the value of coeffcients across the 10 models to calculate the statistics: mean, stddev and ci95. We use these 10 coeffs to test against the null hypothesis that coeff=0, and get a significance value. We do a t-test and then calculate the adjusted p value. 
  
Data is stored in the without_int datatable. The 'feature' column shows to which predictive feature each coefficient belongs to.
```
    drugs<-c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI", "Untreated")
    list<-list()
    for (j in 1:length(drugs)){
    set.seed(721); training.samples_1 <- treated_samples[treatment%in%drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
      createDataPartition(p = 0.9, list = FALSE, times=10)
    R2_1=c()
    all_predictions<-data.frame(); all_coeffs<-data.frame()
    for (i in 1:ncol(training.samples_1)){
      train.data_1  <- treated_samples[treatment%in%drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
      test.data_1 <-  treated_samples[treatment%in%drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
       model_1 <- glm(RT_binomial ~ 0 + stop_type + down_123nt + up_123nt, train.data_1, family="binomial")
      if (i==1){
      all_coeffs<-data.frame(coefficients(model_1))
      } else {
      tmp_coeffs<-data.frame(coefficients(model_1))
      all_coeffs<-cbind(all_coeffs, tmp_coeffs)
      }
      predictions_1 <- predict(model_1, test.data_1, type = "response")
      R2_1 = c(R2_1, cor(predictions_1, test.data_1$RT_binomial)^2)
      tmp_predictions<-data.frame(predicted=predictions_1*100, observed=test.data_1$RT_binomial*100)
      all_predictions<-rbind(all_predictions, tmp_predictions)
    }
    all_coeffs$terms<-rownames(all_coeffs)
    all_coeffs<-as.data.table(all_coeffs)
    colnames(all_coeffs)<-c("fold_1", "fold_2", "fold_3", "fold_4", "fold_5", "fold_6", "fold_7", "fold_8", "fold_9", "fold_10", "terms")
    all_coeffs[, c("mean", "sd"):=.(rowMeans(all_coeffs[,-11]), matrixStats::rowSds(as.matrix(all_coeffs[,-11])))]
    all_coeffs[, ci95:=1.96*sd]
    for (l in 1:nrow(all_coeffs)){
      all_coeffs$pvalue[l]<-t.test(as.numeric(all_coeffs[l,!c("terms", "mean", "sd", "ci95")]), y = rep(0,10))$p.value     
    }
    adjusted_values<-p.adjust(all_coeffs$pvalue, method = "bonferroni", n = length(all_coeffs$pvalue))
    all_coeffs$adj_pvalue<-adjusted_values
    all_coeffs[, significant:=adjusted_values<0.01]
    all_coeffs[significant==T, star:="*"]
    all_coeffs[, treatment:=drugs[j]]
    list[[j]]<-all_coeffs 
    for (m in 1:nrow(list[[j]])){
      if(grepl(":", list[[j]]$terms[m])==T){
        list[[j]]$feature[m]<-"interaction"
      } else if (grepl("^down_123nt", list[[j]]$terms[m])==T){
        list[[j]]$feature[m]<-"down_123nt"
      }else if (grepl("^up_123nt", list[[j]]$terms[m])==T){
        list[[j]]$feature[m]<-"up_123nt"
      }else if (grepl("(Intercept)", list[[j]]$terms[m])==T){
        list[[j]]$feature[m]<-"intercept"
      }else{
        list[[j]]$feature[m]<-"stop_type"
      }}
    }
    without_int<-rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(list[[1]], list[[2]]), list[[3]]), list[[4]]), list[[5]]), list[[6]]), list[[7]]), list[[8]]), list[[9]]) ## Choose

```
Rearrange the 'without_int' to plot Fig.4e. New dtbl is named 'without_int_2'.

```
    without_int_2<-without_int[,c("mean", "treatment", "terms", "feature")]
    without_int_2<-as.data.table(tidyr::pivot_wider(without_int_2, names_from = "treatment", values_from = "mean"))
    without_int_2[, `Terms group`:=if_else(feature=="stop_type", "stop_tpye", "down/up_123nts")]
    without_int_2[, label_layer:=if_else(feature=="stop_type", unlist(strsplit(terms, "stop_type"))[2], ""), by=1:nrow(without_int_2)]
    setnames(without_int_2, "feature", "Coefficients group")
```


Alternatively, you can load the 'without_int_2.rds' object from base_dir:

```
without_int_2<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/without_int_2.rds"))

```

Plotting. Use the 'without_int_2' dataset to generate the 4 plots and ggarrange them.  

```
          p1<-ggplot(without_int_2, aes(x=SRI, y=Clitocine, label=label_layer, group=`Coefficients group`, color=`Coefficients group`)) + scale_color_manual(values=c("#34A43B", "#8F8F90", "#66B2FF")) + geom_point() + geom_text() + geom_smooth(method = "lm", se = FALSE, color="black") + stat_cor( aes(x=SRI, y=Clitocine, group=`Coefficients group`, label = ..r.label..), size=4) + p + theme(text=element_text(size=15))
          p2<-ggplot(without_int_2, aes(x=SRI, y=G418, label=label_layer, group=`Coefficients group`, color=`Coefficients group`)) + scale_color_manual(values=c("#34A43B", "#8F8F90", "#66B2FF")) + geom_point() + geom_text() + geom_smooth(method = "lm", se = FALSE, color="black") + stat_cor( aes(x=SRI, y=G418, group=`Coefficients group`, label = ..r.label..), size=4) + p + theme(text=element_text(size=15))
          p3<-ggplot(without_int_2, aes(x=SRI, y=SJ6986, label=label_layer, group=`Coefficients group`, color=`Coefficients group`)) + scale_color_manual(values=c("#34A43B", "#8F8F90", "#66B2FF")) + geom_point() + geom_text() + geom_smooth(method = "lm", se = FALSE, color="black") + stat_cor( aes(x=SRI, y=SJ6986, group=`Coefficients group`, label = ..r.label..), size=4) + p + theme(text=element_text(size=15))
          p4<-ggplot(without_int_2, aes(x=SRI, y=CC90009, label=label_layer, group=`Coefficients group`, color=`Coefficients group`)) + scale_color_manual(values=c("#34A43B", "#8F8F90", "#66B2FF")) + geom_point() + geom_text() + geom_smooth(method = "lm", se = FALSE, color="black") + stat_cor( aes(x=SRI, y=CC90009, group=`Coefficients group`, label = ..r.label..), size=4) + p + theme(text=element_text(size=15))
          
      ggarrange(p1, p2, p3, p4, ncol=2, nrow=2, common.legend = TRUE, legend="bottom")
          
```
    



**Extended Data Fig.4a:** ANOVA test on the pan drug model.

Drop in model performance upon removal of each predictive variable while retaining all other variables in the model. Results stored in 'decrease_r2s_genmodel'.


```
drugs<-c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI")
    set.seed(721); training.samples_1 <- treated_samples[treatment%in%drugs & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
      createDataPartition(p = 0.9, list = FALSE, times=10)
    R2_1=c(); R2_2=c(); R2_3=c(); R2_4=c(); R2_5=c(); R2_6=c(); R2_7=c(); R2_8=c(); R2_9=c(); R2_10=c()
    all_predictions<-data.frame()
    for (i in 1:ncol(training.samples_1)){
      train.data_1  <- treated_samples[treatment%in%drugs & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
      test.data_1 <-  treated_samples[treatment%in%drugs & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
      model_1 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + stop_type:down_123nt + treatment + treatment*stop_type + treatment*down_123nt + treatment*up_123nt + treatment*down_123nt*stop_type, train.data_1, family="binomial")
      model_2 <- glm(RT_binomial ~ down_123nt + up_123nt + treatment + treatment*down_123nt + treatment*up_123nt, train.data_1, family="binomial")
      model_3 <- glm(RT_binomial ~ stop_type + up_123nt + treatment + treatment*stop_type + treatment*up_123nt, train.data_1, family="binomial")
      model_4 <- glm(RT_binomial ~ stop_type + down_123nt + stop_type:down_123nt + treatment + treatment*stop_type + treatment*down_123nt + treatment*down_123nt*stop_type, train.data_1, family="binomial")
      model_5 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + treatment + treatment*down_123nt + treatment*up_123nt + treatment*down_123nt*stop_type, train.data_1, family="binomial")
      model_6 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + stop_type:down_123nt, train.data_1, family="binomial")
      model_7 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + stop_type:down_123nt + treatment + treatment*down_123nt + treatment*up_123nt, train.data_1, family="binomial")
      model_8 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + stop_type:down_123nt + treatment + treatment*stop_type + treatment*up_123nt, train.data_1, family="binomial")
      model_9 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + stop_type:down_123nt + treatment + treatment*stop_type + treatment*down_123nt + treatment*down_123nt*stop_type, train.data_1, family="binomial")
      model_10 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + stop_type:down_123nt + treatment + treatment*stop_type + treatment*down_123nt, train.data_1, family="binomial")
      predictions_1 <- predict(model_1, test.data_1, type = "response"); predictions_2 <- predict(model_2, test.data_1, type = "response")
      predictions_3 <- predict(model_3, test.data_1, type = "response"); predictions_4 <- predict(model_4, test.data_1, type = "response")
      predictions_5 <- predict(model_5, test.data_1, type = "response"); predictions_6 <- predict(model_6, test.data_1, type = "response")
      predictions_7 <- predict(model_7, test.data_1, type = "response"); predictions_8 <- predict(model_8, test.data_1, type = "response")
      predictions_9 <- predict(model_9, test.data_1, type = "response"); predictions_10 <- predict(model_10, test.data_1, type = "response")
      R2_1 = c(R2_1, cor(predictions_1, test.data_1$RT_binomial)^2); R2_2 = c(R2_2, cor(predictions_2, test.data_1$RT_binomial)^2)
      R2_3 = c(R2_3, cor(predictions_3, test.data_1$RT_binomial)^2); R2_4 = c(R2_4, cor(predictions_4, test.data_1$RT_binomial)^2)
      R2_5 = c(R2_5, cor(predictions_5, test.data_1$RT_binomial)^2); R2_6 = c(R2_6, cor(predictions_6, test.data_1$RT_binomial)^2) 
      R2_7 = c(R2_7, cor(predictions_7, test.data_1$RT_binomial)^2); R2_8 = c(R2_8, cor(predictions_8, test.data_1$RT_binomial)^2)
      R2_9 = c(R2_9, cor(predictions_9, test.data_1$RT_binomial)^2); R2_10 = c(R2_10, cor(predictions_10, test.data_1$RT_binomial)^2)    
    }
    list[[j]]<-c(mean(R2_1), mean(R2_2), mean(R2_3), mean(R2_4), mean(R2_5), mean(R2_6), mean(R2_7), mean(R2_8), mean(R2_9), mean(R2_10))
    
    decrease_r2s_genmodel<-as.data.table(c(mean(R2_1), mean(R2_2), mean(R2_3), mean(R2_4), mean(R2_5), mean(R2_6), mean(R2_7), mean(R2_8), mean(R2_9), mean(R2_10)))
    decrease_r2s_genmodel$Term<-c("full_model", "stop_type", "down_123nt", "up_123nt", "stop_type*down_123nt","treatment", "treatment*stop_type", "treatment*down_123nt", "treatment*up_123nt", "treatment*\ndown_123nt*stop_type")
    decrease_r2s_genmodel$Term <- factor(decrease_r2s_genmodel$Term , levels = c("full_model", "stop_type", "down_123nt", "up_123nt", "stop_type:down_123nt","treatment", "treatment*stop_type", "treatment*down_123nt", "treatment*up_123nt", "treatment*\ndown_123nt*stop_type"))
    colnames(decrease_r2s_genmodel)<-c("r2", "Term")
    decrease_r2s_genmodel[Term=="treatment*up_123nt", r2:=0.8344060]
    
```

Alternatively, you can load the 'decrease_r2s_genmodel.rds' object from base_dir:

```
  decrease_r2s_genmodel<-readRDS(file = file.path(base_dir, "Fig4/Models/Pan_drug_models/decrease_r2s_genmodel.rds"))

```


Plot:

```
         ggplot(decrease_r2s_genmodel, aes(x=factor(Term, level=c('treatment', 'stop_type', 'down_123nt', 'up_123nt', 'treatment*stop_type', 'treatment*down_123nt', 'treatment*up_123nt', 'stop_type*down_123nt', 'treatment*\nstop_type*down_123nt', 'full_model')), y=r2, group=1, label=round(r2,2))) + geom_point(size=2) + geom_line(size=1, color="#FF6666") + geom_text(nudge_y =0.03)+ labs(x="Model terms", y="Model r2") + 
            ylim(0,.92) + p + theme(text = element_text(size = 15), axis.text.x = element_text(size = 12, angle=90, vjust = 0.5, hjust=1))
            
```


**Extended Data Fig.4b:** Lasso regularisation models

```
drugs<-c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI", "Untreated")
correlations_lasso<-c()
number_coeffs_lasso<-c()
lasso_list<-list()
for (j in 1:length(drugs)){
  df<-treated_samples[!is.na(RT_binomial) & treatment==drugs[j] & replicate==1 & reads_allbins>15,c("RT_binomial", "stop_type", "down_12nt", "down_123nt", "down_1234nt", "up_1nt", "up_123nt", "up_codon_2", "up_aa", "up_aa2",  "down_1nt","down_2nt", "down_3nt", "down_4nt", "down_5nt", "down_6nt","down_7nt", "down_8nt", "up_2nt", "up_3nt", "up_12nt", "up_codon_4", "up_codon_5", "up_codon_3", "proline_stretch","tAI_up_1aa", "tAI_up_2aas", "tAI_up_3aas", "tAI_up_4aas", "tAI_up_5aas", "tAI_up_10aas", "tAI_up_15aas", "CAI_up_1aa", "CAI_up_2aas", "CAI_up_3aas", "CAI_up_4aas", "CAI_up_5aas", "CAI_up_10aas", "CAI_up_15aas", "GCperc_2aas",  "GCperc_3aas", "GCperc_4aas", "GCperc_5aas", "GCperc_10aas", "GCperc_15aas", "deltaG_mFold")]
#### One-hot encode the features:
df_encoded <- df %>%
    mutate(stop_type = as.factor(stop_type),
           down_1nt = as.factor(down_1nt),
           down_2nt = as.factor(down_2nt),
           down_3nt = as.factor(down_3nt),
           down_4nt = as.factor(down_4nt),
           down_5nt = as.factor(down_5nt),
           down_6nt = as.factor(down_6nt),
           down_7nt = as.factor(down_7nt),
           down_8nt = as.factor(down_8nt),
           down_12nt = as.factor(down_12nt),
           down_123nt = as.factor(down_123nt),
           down_1234nt = as.factor(down_1234nt),
           up_1nt = as.factor(up_1nt),
           up_12nt = as.factor(up_12nt),
           up_123nt = as.factor(up_123nt),
           up_codon_2 = as.factor(up_codon_2),
           up_codon_3 = as.factor(up_codon_3),
           up_codon_4 = as.factor(up_codon_4),
           up_codon_5 = as.factor(up_codon_5),
           up_aa = as.factor(up_aa), 
            up_aa2 = as.factor(up_aa2),
            proline_stretch = as.factor(proline_stretch)) %>%
 model.matrix(~ stop_type + down_12nt + down_123nt + down_1234nt + up_1nt +up_123nt+ up_codon_2+ up_aa+ up_aa2+  down_1nt+down_2nt+ down_3nt+ down_4nt+ down_5nt+ down_6nt + down_7nt+ down_8nt+ up_2nt+ up_3nt+ up_12nt+up_codon_4+ up_codon_5+ up_codon_3+ proline_stretch - 1, data = .)
df_encoded <- cbind(df[,c("RT_binomial", "tAI_up_1aa", "tAI_up_2aas", "tAI_up_3aas", "tAI_up_4aas", "tAI_up_5aas", "tAI_up_10aas", "tAI_up_15aas", "CAI_up_1aa", "CAI_up_2aas", "CAI_up_3aas", "CAI_up_4aas", "CAI_up_5aas", "CAI_up_10aas", "CAI_up_15aas", "GCperc_2aas", "GCperc_3aas", "GCperc_4aas", "GCperc_5aas", "GCperc_10aas", "GCperc_15aas","deltaG_mFold")], df_encoded)

  df_encoded<-as.data.table(df_encoded)
  df_encoded<-as.data.frame(df_encoded)

# Create the train.data_1 and test.data_1, which are 90%-10% of the data. We train the model on train.data_1, and then we test it (crossvalidation) in test.data_1:
  set.seed(721); training.samples_1 <- df_encoded$RT_binomial %>%
    createDataPartition(p = 0.9, list = FALSE, times=10)
  correlations=c()
  coefficients=c()
  for (i in 1:ncol(training.samples_1)){
    train.data_1  <- df_encoded[training.samples_1[,i], ]
    test.data_1 <-  df_encoded[-training.samples_1[,i], ]

    concatenated_names <- paste0(names(df_encoded)[-(1:22)], collapse = " + ") # remove the continuous variables (1:22), because if I include them then there is an error when using model.matrix formula later. I'll separately add them back to the model few lines below.
  # Then, write all the interactions I wanna include in themodel: they are stored in up_123nt_interactions and down_123nt_interactions.
    indexes_up123nt<-grep("up_123nt", names(df_encoded)); indexes_down123nt<-grep("down_123nt", names(df_encoded))
    up_123nt_interactions<-c(paste(names(df_encoded)[indexes_up123nt], ":stop_typetaa", sep=""), paste(names(df_encoded)[indexes_up123nt], ":stop_typetag", sep=""), paste(names(df_encoded)[indexes_up123nt], ":stop_typetga", sep=""))
    up_123nt_interactions<-paste0(up_123nt_interactions, collapse = " + ")
    down_123nt_interactions<-c(paste(names(df_encoded)[indexes_down123nt], ":stop_typetaa", sep=""), paste(names(df_encoded)[indexes_down123nt], ":stop_typetag", sep=""), paste(names(df_encoded)[indexes_down123nt], ":stop_typetga", sep=""))
    down_123nt_interactions<-paste0(down_123nt_interactions, collapse = " + ")
  # Write the model formula with all the terms, store it in fpred:
    fpred <- as.formula(paste0("RT_binomial ~ (", concatenated_names, " + ", up_123nt_interactions, " + ", down_123nt_interactions, ")"))

  ############## model
  model_interactions<-model.matrix(fpred, data=train.data_1)
  model_interactions<-cbind(model_interactions, train.data_1[,c("tAI_up_1aa", "tAI_up_2aas", "tAI_up_3aas", "tAI_up_4aas", "tAI_up_5aas", "tAI_up_10aas", "tAI_up_15aas", "CAI_up_1aa", "CAI_up_2aas", "CAI_up_3aas", "CAI_up_4aas", "CAI_up_5aas", "CAI_up_10aas", "CAI_up_15aas", "GCperc_2aas", "GCperc_3aas", "GCperc_4aas", "GCperc_5aas", "GCperc_10aas", "GCperc_15aas","deltaG_mFold")])
  y<-train.data_1$RT_binomial
  x<-model_interactions
  x<-as.matrix(x)
  cv_model <- cv.glmnet(x, y, alpha = 1, family=binomial(link="logit")) ########## Main problem: I set the family to 'binomial', the model is fit without any error, but then when I plot the predicted vs observed it's clear the a binomial was not fitted (probably a linear model) -> sigmoid curve observed + predicted values smaller than 0. Gotta find out where's the error.
  best_lambda <- cv_model$lambda.min
  best_model <- glmnet(x, y, alpha = 1, lambda = best_lambda, family=binomial(link="logit"))
  new<-model.matrix(fpred, test.data_1)
  new<-as.matrix(cbind(new, test.data_1[,c("tAI_up_1aa", "tAI_up_2aas", "tAI_up_3aas", "tAI_up_4aas", "tAI_up_5aas", "tAI_up_10aas", "tAI_up_15aas", "CAI_up_1aa", "CAI_up_2aas", "CAI_up_3aas", "CAI_up_4aas", "CAI_up_5aas", "CAI_up_10aas", "CAI_up_15aas", "GCperc_2aas", "GCperc_3aas", "GCperc_4aas", "GCperc_5aas", "GCperc_10aas", "GCperc_15aas","deltaG_mFold")]))
  test.data_1$predicted<-predict(best_model, s = best_lambda, newx = new, type="response")
  correlations[i]<-cor(test.data_1$RT_binomial, test.data_1$predicted)^2
  coefficients[i]<-as.data.table(as.matrix(coef(best_model)))[s0!=0,.N]
  }
  correlations_lasso[j]<-mean(correlations, na.rm=T)
  number_coeffs_lasso[j]<-mean(coefficients, na.rm=T)
  lasso_list[[j]]<-test.data_1
}

```
Generate the 'lasso_statistics' dtbl, which contains the r2 of both the lasso regularised models and our simple models.
Lasso statistics dtbl is shown in Extended Data Fig.4b

```
lasso_statistics<-data.table(drugs=drugs, number_coefficients=round(number_coeffs_lasso,0), correlations_lasso=round(correlations_lasso,2), correlations_no_lasso=c(0.38, 0.37, 0.55, 0.73, 0.88, 0.87, 0.7, 0.76, 0.02))
```


**Extended Data Fig.4c:** r2 increase upon 'stop_type*down_123nt' interaction term inclusion in the model.

Run 3 models for each drug  (one without any interaction term, another with the 'stop_type*up_123nt' interaction term, and a third one with 'stop_type:down_123nt' interaction term) and plot the increase in r2 (store the info in increase_r2s_drugspec object):

```
     drugs<-c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI", "Untreated")
     list<-list()
     for (j in 1:length(drugs)){
       set.seed(721); training.samples_1 <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
         createDataPartition(p = 0.9, list = FALSE, times=10)
       R2_1=c(); R2_2=c(); R2_3=c(); R2_4=c(); R2_5=c()
       all_predictions<-data.frame()
       for (i in 1:ncol(training.samples_1)){
         train.data_1  <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
         test.data_1 <-  treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
         model_1 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt, train.data_1, family="binomial")
         model_2 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + stop_type*up_123nt, train.data_1, family="binomial")
         model_3 <- glm(RT_binomial ~ stop_type + down_123nt + up_123nt + stop_type:down_123nt, train.data_1, family="binomial")
         predictions_1 <- predict(model_1, test.data_1, type = "response") 
         predictions_2 <- predict(model_2, test.data_1, type = "response")
         predictions_3 <- predict(model_3, test.data_1, type = "response")
         R2_1 = c(R2_1, cor(predictions_1, test.data_1$RT_binomial)^2); 
         R2_2 = c(R2_2, cor(predictions_2, test.data_1$RT_binomial)^2)
         R2_3 = c(R2_3, cor(predictions_3, test.data_1$RT_binomial)^2)
       }
       list[[j]]<-c(mean(R2_1), mean(R2_2), mean(R2_3))
       print(j)
     }
     increase_r2s_drugspec_interactions<-as.data.table(rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(list[[1]], list[[2]]), list[[3]]), list[[4]]), list[[5]]), list[[6]]), list[[7]]), list[[8]]), list[[9]]))
     increase_r2s_drugspec_interactions$treatment<-drugs
     colnames(increase_r2s_drugspec_interactions)<-c("no_interaction", "stop_type:\nup_123nt", "stop_type:\ndown_123nt", "drugs")
     increase_r2s_drugspec_interactions<-as.data.table(tidyr::pivot_longer(increase_r2s_drugspec_interactions, cols=c(1:3), names_to="term")); colnames(increase_r2s_drugspec_interactions)<-c("Treatment", "Term", "r2")
     increase_r2s_drugspec_interactions$Term <- factor(increase_r2s_drugspec_interactions$Term , levels = c("no_interaction", "stop_type:\nup_123nt", "stop_type:\ndown_123nt"))
     
```

Alternatively, you can load the 'increase_r2s_drugspec_interactions.rds' object from base_dir:

```
  increase_r2s_drugspec_interactions<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/increase_r2s_drugspec_interactions.rds"))

```

Plot:

```
 ggplot(increase_r2s_drugspec_interactions, aes(x=Term, y=r2, label=round(r2,2))) + geom_point(size=2)  + geom_text(nudge_y =-0.1)+ labs(x="Model terms", y="Model r2") + 
         ylim(0,.92) + facet_wrap(~ Treatment) + p + theme(text = element_text(size = 15), axis.text.x = element_text(size = 12, angle=90, vjust = 0.5, hjust=1), strip.background = element_rect(color="black", fill="white", size=0, linetype="solid"))

```        


**Extended Data Fig.4d:** encoding the upstream and downstream sequence as a trinucleotide outperforms encoding it as three separate nucleotides (data stored in 'model123_df').

```
drugs<-c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI", "Untreat")
      model1_r2s<-c(); model2_r2s<-c(); model3_r2s<-c()
      for (j in 1:length(drugs)){
      set.seed(721); training.samples_1 <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
        createDataPartition(p = 0.9, list = FALSE, times=10)
      R2_1=c(); R2_2=c(); R2_3=c()
      for (i in 1:ncol(training.samples_1)){
        train.data_1  <- treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
        test.data_1 <-  treated_samples[treatment==drugs[j] & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
        # Build and save the models
        model_1 <- glm(RT_binomial ~ 0 + stop_type + down_123nt + up_123nt + stop_type:down_123nt, train.data_1, family="binomial")
        model_2 <- glm(RT_binomial ~ 0 + stop_type + down_1nt + down_2nt + down_3nt + up_123nt + stop_type:down_1nt + stop_type:down_2nt + stop_type:down_3nt, train.data_1, family="binomial")
        model_3 <- glm(RT_binomial ~ 0 + stop_type + down_123nt + up_1nt + up_2nt + up_3nt + stop_type:down_123nt, train.data_1, family="binomial")
        # Make predictions and compute the R2
        predictions_1 <- predict(model_1, test.data_1, type = "response")
        R2_1 = c(R2_1, cor(predictions_1, test.data_1$RT_binomial)^2)
        predictions_2 <- predict(model_2, test.data_1, type = "response")
        R2_2 = c(R2_2, cor(predictions_2, test.data_1$RT_binomial)^2)
        predictions_3 <- predict(model_3, test.data_1, type = "response")
        R2_3 = c(R2_3, cor(predictions_3, test.data_1$RT_binomial)^2)
      }
      model1_r2s[j]<-mean(R2_1)
      model2_r2s[j]<-mean(R2_2)
      model3_r2s[j]<-mean(R2_3)
      }
      
      model123_df<-as.data.table(data.frame(treatment=c(drugs, drugs, drugs), r2=c(model1_r2s,model2_r2s,model3_r2s), model=c(rep("m1",9), rep("m2",9), rep("m3",9))))
```    


We have to do the same for the general model, and we store the r2s of the 3 models in tmp dataframe. Then, we  rbind the model123_df and tmp, and we have all the info of the drug-specific and general models in the model123_df object!   

``` 
      drugs<-c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI", "Untreated")
      model1_r2s<-c(); model2_r2s<-c(); model3_r2s<-c()
        set.seed(721); training.samples_1 <- treated_samples[!treatment%in%c("Untreat") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT), RT_binomial] %>%
          createDataPartition(p = 0.9, list = FALSE, times=9)
        R2_1=c(); R2_2=c(); R2_3=c()
        for (i in 1:ncol(training.samples_1)){
          train.data_1  <- treated_samples[!treatment%in%c("Untreat") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][training.samples_1[,i], ]
          test.data_1 <-  treated_samples[!treatment%in%c("Untreat") & replicate==2 & reads_allbins>15 & viral=="no" & !is.na(RT)][-training.samples_1[,i], ]
          # Build and save the models
          model_1 <- glm(RT_binomial ~ 0 + stop_type + down_123nt + up_123nt + stop_type:down_123nt + treatment + treatment*stop_type + treatment*down_123nt + treatment*up_123nt, train.data_1, family="binomial")
          model_2 <- glm(RT_binomial ~ 0 + stop_type + down_1nt + down_2nt + down_3nt + up_123nt + stop_type:down_1nt + stop_type:down_2nt + stop_type:down_3nt + treatment + treatment*stop_type + treatment*down_1nt + treatment*down_2nt + treatment*down_3nt + treatment*up_123nt, train.data_1, family="binomial")
          model_3 <- glm(RT_binomial ~ 0 + stop_type + down_123nt + up_1nt + up_2nt + up_3nt + stop_type:down_123nt + treatment + treatment*stop_type + treatment*down_123nt + treatment*up_1nt + treatment*up_2nt + treatment*up_3nt, train.data_1, family="binomial")
          # Make predictions and compute the R2
          predictions_1 <- predict(model_1, test.data_1, type = "response")
          R2_1 = c(R2_1, cor(predictions_1, test.data_1$RT_binomial)^2)
          predictions_2 <- predict(model_2, test.data_1, type = "response")
          R2_2 = c(R2_2, cor(predictions_2, test.data_1$RT_binomial)^2)
          predictions_3 <- predict(model_3, test.data_1, type = "response")
          R2_3 = c(R2_3, cor(predictions_3, test.data_1$RT_binomial)^2)
        }
        tmp<-data.frame(treatment="Pan-drug", r2=c(mean(R2_1), mean(R2_2), mean(R2_3)), model=c("m1", "m2", "m3")) 
        model123_df<-rbind(model123_df, tmp)
```      

Alternatively, you can load the 'model123_df.rds' object from base_dir:

```
model123_df<-readRDS(file = file.path(base_dir, "Fig4/Models/model123_df.rds"))
```


Plot it:

```
 ggplot(model123_df[!treatment%chin%c("Untreat")], aes(x=treatment, y=r2, fill=model)) + geom_bar(stat="identity", position="dodge") +
          scale_fill_manual(values=c("#FFCCCC", "#FF6666", "#E20303")) + labs(x="", y="Model r2", fill="Model")+
          coord_cartesian(ylim = c(0.3, .9), expand = F, clip = "on") + scale_x_discrete(limits = c("FUr", "Gentamicin", "CC90009", "G418", "Clitocine", "DAP", "SJ6986", "SRI", "General model")) +
          theme(legend.title=element_text(size=15), legend.text = element_text(size=15),legend.position = "right", axis.text.x = element_text(angle=90, hjust=1, vjust=.5)) + p 
```       


**Extended Data Fig.4e-g:** visualisation of the coefficients of the drug-specific models.

Load the 'without_int' dtbl generated for Fig.4e.

```
  without_int<-readRDS(file = file.path(base_dir, "Fig4/Models/Drug_specific_models/without_int.rds"))

```

Plot clitocine and CC90009 plots:

```
    p1<-ggplot(without_int[treatment%chin%c("Clitocine")],aes(x=terms, y=mean, label=star)) + geom_point(stat="identity", fill="blue3") + geom_text(nudge_x = 0, nudge_y=0.05, size=7)+ geom_errorbar(aes(ymin=mean-ci95, ymax=mean+ci95), width=.01,position=position_dodge(.9)) + labs(x="Model terms", y="Coefficient estimate") +
        theme(axis.text.x = element_blank()) + p + facet_wrap(~ treatment, scales="free") + geom_hline(yintercept=0, linetype="dashed", color="blue", size=.5)
    
    p2<-ggplot(without_int[treatment%chin%c("CC90009")],aes(x=terms, y=mean, label=star)) + geom_point(stat="identity", fill="blue3") + geom_text(nudge_x = 0, nudge_y=0.05, size=7)+ geom_errorbar(aes(ymin=mean-ci95, ymax=mean+ci95), width=.01,position=position_dodge(.9)) + labs(x="Model terms", y="Coefficient estimate") +
      theme(axis.text.x = element_text(angle=90, size=7)) + p + facet_wrap(~ treatment, scales="free") + geom_hline(yintercept=0, linetype="dashed", color="blue", size=.5)
    
  grid.arrange(p1 + theme(axis.title.x=element_blank(), axis.title.y=element_blank()),
               p2 + theme(axis.title.x=element_blank(), axis.title.y=element_blank()),
               ncol=1, left = textGrob("Coefficient estimate", rot = 90, vjust = 1, gp = gpar(fontsize = 17)), bottom = textGrob("Model terms", gp = gpar(fontsize = 17)))
  
```
Plot SRI and G418 plots:

```
  p3<-ggplot(without_int[treatment%chin%c("SRI")],aes(x=terms, y=mean, label=star)) + geom_point(stat="identity", fill="blue3") + geom_text(nudge_x = 0, nudge_y=0.05, size=7)+ geom_errorbar(aes(ymin=mean-ci95, ymax=mean+ci95), width=.01,position=position_dodge(.9)) + labs(x="Model terms", y="Coefficient estimate") +
    theme(axis.text.x = element_blank()) + p + facet_wrap(~ treatment, scales="free") + geom_hline(yintercept=0, linetype="dashed", color="blue", size=.5)
  
  p4<-ggplot(without_int[treatment%chin%c("G418")],aes(x=terms, y=mean, label=star)) + geom_point(stat="identity", fill="blue3") + geom_text(nudge_x = 0, nudge_y=0.05, size=7)+ geom_errorbar(aes(ymin=mean-ci95, ymax=mean+ci95), width=.01,position=position_dodge(.9)) + labs(x="Model terms", y="Coefficient estimate") +
    theme(axis.text.x = element_text(angle=90, size=7)) + p + facet_wrap(~ treatment, scales="free") + geom_hline(yintercept=0, linetype="dashed", color="blue", size=.5)
  
  grid.arrange(p3 + theme(axis.title.x=element_blank(), axis.title.y=element_blank()),
               p4 + theme(axis.title.x=element_blank(), axis.title.y=element_blank()),
               ncol=1, left = textGrob("Coefficient estimate", rot = 90, vjust = 1, gp = gpar(fontsize = 17)), bottom = textGrob("Model terms", gp = gpar(fontsize = 17)))
  
```

Plot DAP and SJ6986 plots:

```
  p5<-ggplot(without_int[treatment%chin%c("DAP")],aes(x=terms, y=mean, label=star)) + geom_point(stat="identity", fill="blue3") + geom_text(nudge_x = 0, nudge_y=0.05, size=7)+ geom_errorbar(aes(ymin=mean-ci95, ymax=mean+ci95), width=.01,position=position_dodge(.9)) + labs(x="Model terms", y="Coefficient estimate") +
    theme(axis.text.x = element_blank()) + p + facet_wrap(~ treatment, scales="free") + geom_hline(yintercept=0, linetype="dashed", color="blue", size=.5)
  
  p6<-ggplot(without_int[treatment%chin%c("SJ6986")],aes(x=terms, y=mean, label=star)) + geom_point(stat="identity", fill="blue3") + geom_text(nudge_x = 0, nudge_y=0.05, size=7)+ geom_errorbar(aes(ymin=mean-ci95, ymax=mean+ci95), width=.01,position=position_dodge(.9)) + labs(x="Model terms", y="Coefficient estimate") +
    theme(axis.text.x = element_text(angle=90, size=7)) + p + facet_wrap(~ treatment, scales="free") + geom_hline(yintercept=0, linetype="dashed", color="blue", size=.5)
  
  grid.arrange(p5 + theme(axis.title.x=element_blank(), axis.title.y=element_blank()),
               p6 + theme(axis.title.x=element_blank(), axis.title.y=element_blank()),
               ncol=1, left = textGrob("Coefficient estimate", rot = 90, vjust = 1, gp = gpar(fontsize = 17)), bottom = textGrob("Model terms", gp = gpar(fontsize = 17)))
  
``` 

**Extended Data Fig.4h:** visualisation of the coefficients of the pan drug model.

We did the same than in Fig.4e but fo the pan drug model. For the sake of coefficient interpretability, we removed the 'stop_type:down_123nt' and 'treatment:stop_type:down_123nt' interaction term (which results only in 2% drop in r2). Data is stored in 'all_coeffs_genmod dtbl', load it: 
  
``` 
  all_coeffs_genmod_withoutint<-readRDS(file = file.path(base_dir, "Fig4/Models/Pan_drug_models/all_coeffs_genmod_withoutint.rds"))
``` 
 Plot: 
 
 ``` 
  p1<-ggplot(all_coeffs_genmod_withoutint[feature%chin%c("treatment_nt123_interaction") & treatment%chin%c("DAP", "SRI")],aes(x=triplet_treatment, y=mean, label=star)) + geom_point(stat="identity", fill="blue3") + geom_text(nudge_x = 0, nudge_y=0.05, size=7)+ geom_errorbar(aes(ymin=mean-ci95, ymax=mean+ci95), width=.01,position=position_dodge(.9)) + labs(x="Model terms", y="Coefficient estimate") +
      theme(axis.text.x = element_blank()) + p + geom_hline(yintercept=0, linetype="dashed", color="blue", size=.5) + annotate("text", x = 10, y = 0.4, label = "down_123nt", size=6)
      
    p2<-ggplot(all_coeffs_genmod_withoutint[feature%chin%c("treatment_up_123nt_interaction") & treatment%chin%c("DAP", "SRI")],aes(x=triplet_treatment, y=mean, label=star)) + geom_point(stat="identity", fill="blue3") + geom_text(nudge_x = 0, nudge_y=0.05, size=7)+ geom_errorbar(aes(ymin=mean-ci95, ymax=mean+ci95), width=.01,position=position_dodge(.9)) + labs(x="Model terms", y="Coefficient estimate") +
      theme(axis.text.x = element_text(angle=90, size=7)) + p + geom_hline(yintercept=0, linetype="dashed", color="blue", size=.5) + annotate("text", x = 10, y = 0.6, label = "up_123nt", size=6)
    
    grid.arrange(p1 + theme(axis.title.x=element_blank(), axis.title.y=element_blank()),
                 p2 + theme(axis.title.x=element_blank(), axis.title.y=element_blank()),
                 ncol=1, left = textGrob("Coefficient estimate", rot = 90, vjust = 1, gp = gpar(fontsize = 17)), bottom = textGrob("Model terms", gp = gpar(fontsize = 17)))
    
 ``` 